# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/ESD/ESD_CP/PYNQ-image_v2.7/PYNQ-image_v2.7/boards/Pynq-Z2/base/reduced_version/reduced_version.srcs/sources_1/bd/base/ip/base_xbar_11/base_xbar_11.xci
# IP: The module: 'base_xbar_11' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ESD/ESD_CP/PYNQ-image_v2.7/PYNQ-image_v2.7/boards/Pynq-Z2/base/reduced_version/reduced_version.gen/sources_1/bd/base/ip/base_xbar_11/base_xbar_11_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_xbar_11'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/ESD/ESD_CP/PYNQ-image_v2.7/PYNQ-image_v2.7/boards/Pynq-Z2/base/reduced_version/reduced_version.srcs/sources_1/bd/base/ip/base_xbar_11/base_xbar_11.xci
# IP: The module: 'base_xbar_11' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ESD/ESD_CP/PYNQ-image_v2.7/PYNQ-image_v2.7/boards/Pynq-Z2/base/reduced_version/reduced_version.gen/sources_1/bd/base/ip/base_xbar_11/base_xbar_11_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_xbar_11'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
