#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : base.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sun May 05 17:27:29 +0530 2024
# SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: base.sh [-help]
# usage: base.sh [-lib_map_path]
# usage: base.sh [-noclean_files]
# usage: base.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'base.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_22 fifo_generator_v13_2_5 axi_data_fifo_v2_1_21 axi_crossbar_v2_1_23 xil_defaultlib axi_lite_ipif_v3_0_4 axi_intc_v4_1_15 lib_cdc_v1_0_2 lib_pkg_v1_0_2 lib_fifo_v1_0_14 blk_mem_gen_v8_4_4 lib_bmg_v1_0_13 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_24 axi_vdma_v6_3_10 axis_infrastructure_v1_1_0 axis_register_slice_v1_1_22 v_vid_in_axi4s_v4_0_9 v_tc_v6_2_1 interrupt_control_v3_1_4 axi_gpio_v2_0_24 v_tc_v6_1_13 v_axi4s_vid_out_v4_0_11 xlconcat_v2_1_4 proc_sys_reset_v5_0_13 axi_vip_v1_1_8 processing_system7_vip_v1_0_10 axis_subset_converter_v1_1_22 axi_sg_v4_1_13 axi_dma_v7_1_23 axi_protocol_converter_v2_1_22 axi_clock_converter_v2_1_21 axi_dwidth_converter_v2_1_22)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "base.sh - Script generated by export_simulation (Vivado v2020.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/af2c/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/54c0/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_23 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/bc0a/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_xbar_6/sim/base_xbar_6.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_intc_v4_1_15 $vhdlan_opts \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/47b8/hdl/axi_intc_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_system_interrupts_0/sim/base_system_interrupts_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_xbar_9/sim/base_xbar_9.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_xbar_10/sim/base_xbar_10.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_fifo_v1_0_14 $vhdlan_opts \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/a5cb/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_13 $vhdlan_opts \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/af67/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_24 $vhdlan_opts \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/4ab6/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vdma_v6_3_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_vdma_v6_3_10 $vhdlan_opts \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_axi_vdma_0/sim/base_axi_vdma_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_register_slice_v1_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ebcc/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_axis_register_slice_0_0/sim/base_axis_register_slice_0_0.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/a035/hdl/verilog/color_convert_control_s_axi.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/a035/hdl/verilog/color_convert_mul_10s_8ns_18_1_1.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/a035/hdl/verilog/color_convert_regslice_both.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/a035/hdl/verilog/color_convert.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_color_convert_0/sim/base_color_convert_0.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/4b6f/color_swap.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_color_swap_0_0/sim/base_color_swap_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_vid_in_axi4s_v4_0_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/b2aa/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_v_vid_in_axi4s_0_0/sim/base_v_vid_in_axi4s_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work v_tc_v6_2_1 $vhdlan_opts \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/cd2e/hdl/v_tc_v6_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_vtc_in_0/sim/base_vtc_in_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_24 $vhdlan_opts \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/4318/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_axi_gpio_hdmiin_0/sim/base_axi_gpio_hdmiin_0.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/269e/src/SyncBase.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/269e/src/EEPROM_8b.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/269e/src/TWI_SlaveCtl.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/269e/src/GlitchFilter.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/269e/src/SyncAsync.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/269e/src/DVI_Constants.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/269e/src/SyncAsyncReset.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/269e/src/PhaseAlign.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/269e/src/InputSERDES.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/269e/src/ChannelBond.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/269e/src/ResyncToBUFG.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/269e/src/TMDS_Decoder.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/269e/src/TMDS_Clocking.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/269e/src/dvi2rgb.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_dvi2rgb_0_0/sim/base_dvi2rgb_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/431d/hdl/verilog/pixel_pack_control_s_axi.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/431d/hdl/verilog/pixel_pack_regslice_both.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/431d/hdl/verilog/pixel_pack.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_pixel_pack_0/sim/base_pixel_pack_0.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_axis_register_slice_0_1/sim/base_axis_register_slice_0_1.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_color_convert_1/sim/base_color_convert_1.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/9097/src/mmcme2_drp.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/9097/src/axi_dynclk_S00_AXI.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/9097/src/axi_dynclk.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_axi_dynclk_0/sim/base_axi_dynclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_color_swap_0_1/sim/base_color_swap_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work v_tc_v6_1_13 $vhdlan_opts \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/b92e/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_axi4s_vid_out_v4_0_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/1a1e/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_v_axi4s_vid_out_0_0/sim/base_v_axi4s_vid_out_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_vtc_out_0/sim/base_vtc_out_0.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_hdmi_out_hpd_video_0/sim/base_hdmi_out_hpd_video_0.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/bd5a/src/ClockGen.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/bd5a/src/OutputSERDES.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/bd5a/src/TMDS_Encoder.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/bd5a/src/rgb2dvi.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_rgb2dvi_0_0/sim/base_rgb2dvi_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/0fad/hdl/verilog/pixel_unpack_control_s_axi.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/0fad/hdl/verilog/pixel_unpack_regslice_both.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/0fad/hdl/verilog/pixel_unpack.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_pixel_unpack_0/sim/base_pixel_unpack_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_xlconcat_0_0/sim/base_xlconcat_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_proc_sys_reset_pixelclk_0/sim/base_proc_sys_reset_pixelclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vip_v1_1_8 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/94c3/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_10 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_ps7_0_0/sim/base_ps7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_rst_ps7_0_fclk0_0/sim/base_rst_ps7_0_fclk0_0.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_rst_ps7_0_fclk1_0/sim/base_rst_ps7_0_fclk1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_clk_wiz_0_0/base_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_clk_wiz_0_0/base_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_proc_sys_reset_0_0/sim/base_proc_sys_reset_0_0.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/base_xadc_wiz_0_0_conv_funs_pkg.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/base_xadc_wiz_0_0_proc_common_pkg.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/base_xadc_wiz_0_0_ipif_pkg.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/base_xadc_wiz_0_0_family_support.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/base_xadc_wiz_0_0_family.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/base_xadc_wiz_0_0_soft_reset.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/base_xadc_wiz_0_0_pselect_f.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_xadc_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/base_xadc_wiz_0_0_address_decoder.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_xadc_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/base_xadc_wiz_0_0_slave_attachment.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_xadc_wiz_0_0/interrupt_control_v2_01_a/hdl/src/vhdl/base_xadc_wiz_0_0_interrupt_control.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_xadc_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/base_xadc_wiz_0_0_axi_lite_ipif.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_xadc_wiz_0_0/base_xadc_wiz_0_0_drp_arbiter.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_xadc_wiz_0_0/base_xadc_wiz_0_0_drp_to_axi_stream.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_xadc_wiz_0_0/base_xadc_wiz_0_0_xadc_core_drp.vhd" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_xadc_wiz_0_0/base_xadc_wiz_0_0_axi_xadc.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_xadc_wiz_0_0/base_xadc_wiz_0_0.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_axis_subset_converter_0_0/hdl/tdata_base_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_axis_subset_converter_0_0/hdl/tuser_base_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_axis_subset_converter_0_0/hdl/tstrb_base_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_axis_subset_converter_0_0/hdl/tkeep_base_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_axis_subset_converter_0_0/hdl/tid_base_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_axis_subset_converter_0_0/hdl/tdest_base_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_axis_subset_converter_0_0/hdl/tlast_base_axis_subset_converter_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_subset_converter_v1_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/69d9/hdl/axis_subset_converter_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_axis_subset_converter_0_0/hdl/top_base_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_axis_subset_converter_0_0/sim/base_axis_subset_converter_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_sg_v4_1_13 $vhdlan_opts \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/4919/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_23 $vhdlan_opts \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/89d8/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_axi_dma_0_0/sim/base_axi_dma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/sim/base.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_xbar_11/sim/base_xbar_11.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_axi_intc_0_0/sim/base_axi_intc_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_xlconcat_0_1/sim/base_xlconcat_0_1.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_s00_regslice_52/sim/base_s00_regslice_52.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/5cee/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_auto_pc_1/sim/base_auto_pc_1.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_m00_regslice_52/sim/base_m00_regslice_52.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_auto_pc_0/sim/base_auto_pc_0.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_m01_regslice_52/sim/base_m01_regslice_52.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_s00_regslice_53/sim/base_s00_regslice_53.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_auto_pc_2/sim/base_auto_pc_2.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_m00_regslice_53/sim/base_m00_regslice_53.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_m01_regslice_53/sim/base_m01_regslice_53.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/1304/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_auto_cc_0/sim/base_auto_cc_0.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_m02_regslice_0/sim/base_m02_regslice_0.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_auto_cc_1/sim/base_auto_cc_1.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_m03_regslice_0/sim/base_m03_regslice_0.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_m04_regslice_0/sim/base_m04_regslice_0.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_m05_regslice_0/sim/base_m05_regslice_0.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_m06_regslice_0/sim/base_m06_regslice_0.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_auto_cc_2/sim/base_auto_cc_2.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_m07_regslice_0/sim/base_m07_regslice_0.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_auto_cc_3/sim/base_auto_cc_3.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_m08_regslice_0/sim/base_m08_regslice_0.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_m09_regslice_0/sim/base_m09_regslice_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/2394/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_auto_us_0/sim/base_auto_us_0.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_auto_pc_3/sim/base_auto_pc_3.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_auto_pc_4/sim/base_auto_pc_4.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_auto_us_1/sim/base_auto_us_1.v" \
    "$ref_dir/../../../../reduced_version.gen/sources_1/bd/base/ip/base_auto_pc_5/sim/base_auto_pc_5.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.base xil_defaultlib.glbl -o base_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./base_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./base.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key base_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc base_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./base.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: base.sh [-help]\n\
Usage: base.sh [-lib_map_path]\n\
Usage: base.sh [-reset_run]\n\
Usage: base.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
